name: Build and Deploy .NET App to AKS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: youracrname
      IMAGE_NAME: myapp
      RESOURCE_GROUP: your-resource-group
      AKS_CLUSTER: your-aks-name
      DOTNET_ROOT: /usr/share/dotnet

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish app
      run: dotnet publish -c Release -o out

    - name: Docker build
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .
        echo "Built image: $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}"

    - name: Docker login
      run: az acr login --name $ACR_NAME

    - name: Push image to ACR
      run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

    - name: Set AKS context
      run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER

    - name: Deploy to AKS using Helm
      run: |
        helm upgrade --install myapp ./helm \
          --set image.repository=$ACR_NAME.azurecr.io/$IMAGE_NAME \
          --set image.tag=${{ github.sha }}
